<?php
//INICIAMOS UNA SESION
session_start();

//ESTABLECEMOS LA VARIABLE DE SESION CON LA VARIABLE SUPERGLOBAL _SESSION
$_SESSION["CLAVE"] = "VALOR";

//LIMPIAMOS LOS VALORES DE LA VARIABLE
session_unset();

//DESTRUYE LA SESSION
session_destroy();
?>